version: "3.3"

services:
  web-ui:
    image: docker-registry.dccn.nl:5000/hpc-jobmon-ui:latest
    environment:
      APIHOSTNAME: web-api
      APIPORT: 3000
    networks:
      default:
      proxynet:
        aliases:
          - hpc-jobmon-ui
    configs:
      - source: adconfig.json
        target: /controllers/adconfig.json
    depends_on:
      - web-api
    deploy:
      placement:
        constraints:
          - node.labels.function == production

  web-api:
    image: docker-registry.dccn.nl:5000/hpc-jobmon-api:latest
    configs:
      - source: dbconfig.json
        target: /controllers/dbconfig.json
    depends_on:
      - db
    deploy:
      placement:
        constraints:
          - node.labels.function == production

  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    secrets:
      - mysql-root
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root
      MYSQL_DATABASE: hpc_beta
    volumes:
      - "/mnt/docker/data/hpc-jobmon/mysql:/var/lib/mysql"
      - "/mnt/docker/scripts/microservices/hpc-jobmon/initdb.d:/docker-entrypoint-initdb.d:ro"
    deploy:
      placement:
        constraints:
          - node.labels.function == production

secrets:
  mysql-root:
    file: /mnt/docker/data/hpc-jobmon/mysql-root

networks:
  default:
  proxynet:
    external: true

configs:
  dbconfig.json:
    file: /mnt/docker/data/hpc-jobmon/dbconfig.json
  adconfig.json:
    file: /mnt/docker/data/hpc-jobmon/adconfig.json
